name: Build grav1synth (Windows x64)
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: windows-2022

    env:
      CARGO_INCREMENTAL: 0

      ffmpeg_ver: "7.0"
      ffmpeg_path: "C:/ffmpeg"

    steps:
      - name: FFmpeg installation
        run: |
          $tempFile = New-TemporaryFile
          $uri = 'https://github.com/GyanD/codexffmpeg/releases/download/VER/ffmpeg-VER-full_build-shared.7z'.Replace('VER', "$env:ffmpeg_ver")
          Invoke-WebRequest "$uri" -OutFile "$tempFile" -TimeoutSec 10
          7z x -y -o"$env:ffmpeg_path" "$tempFile"

      - name: FFmpeg environment variable
        run: |
          echo "FFMPEG_DIR=$((Get-ChildItem -Directory "$env:ffmpeg_path").FullName)" | Out-File $env:GITHUB_ENV -Append

      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: grav1synth build
        run: cargo build --release

      - name: Create prerelease
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          tag_name: latest
          files: target/release/grav1synth.exe
          fail_on_unmatched_files: true

